#!/usr/bin/env python
"""
Capture the demo board the web app renders when no API is reachable.

The web app talks to the live API. This snapshot exists for three cases where it cannot: the
first paint before the first answer arrives, a component test, and the offline day view. It is
GENERATED by a real run of the repository's own solver and checker, never typed, so no figure
in the interface can drift from the engine. Rerun it after any change to the solver, the
checker, the rules or the demo data:

    uv run python web/scripts/capture_demo_board.py

Output: web/src/fixtures/demo-board.json, with the run's git SHA and timestamp in the header.
"""
from __future__ import annotations

import json
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from api.hold.pass2 import hold_days_paid, pass2, recount_hold_days, to_solve_result  # noqa: E402
from api.hold.penalties import hold_day_cost_cents  # noqa: E402
from api.hold.schemas import ScheduleInput  # noqa: E402
from api.hold.solve import pass1_schedule  # noqa: E402

TIME_LIMIT = 60.0


def _strip_labels(raw: dict) -> dict:
    return {k: v for k, v in raw.items() if not k.startswith("_")}


def _run_sha() -> str:
    try:
        return subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"], cwd=ROOT, capture_output=True, text=True, check=True
        ).stdout.strip()
    except Exception:
        return "unknown"


def main() -> int:
    demo_raw = json.loads((ROOT / "data" / "demo" / "hold-demo.json").read_text(encoding="utf-8"))
    before_raw = json.loads((ROOT / "data" / "demo" / "before-order.json").read_text(encoding="utf-8"))
    schedule = ScheduleInput.model_validate(_strip_labels(demo_raw))

    day_count = len(schedule.days)
    before_map = {int(k): v for k, v in before_raw["day_scene_ids"].items()}
    before_full = {d: before_map.get(d, []) for d in range(day_count)}

    before_verdicts = [p.verdict for p in pass1_schedule(schedule, day_scene_ids=before_full, time_limit_s=TIME_LIMIT)]
    before_held = recount_hold_days(schedule, before_map)
    before_hold_days = sum(len(v) for v in before_held.values())

    solved = pass2(schedule, time_limit_s=TIME_LIMIT)
    after = to_solve_result(solved)
    after_map = {int(d): list(ids) for d, ids in solved.day_scene_ids.items()}

    # The cost of a hold day is NOT the day rate. It carries pension and health, and it is only
    # paid for cast the agreement pays consecutively. api/hold/facts.py is the authority for this
    # figure and this file calls the same function rather than recomputing it: an earlier version
    # of this script multiplied the raw day rate and published $3,336.00 against the project's own
    # $4,069.92. The assertion below is what makes that impossible to ship again.
    paid = hold_days_paid(schedule)
    cast_by_id = {member.id: member for member in schedule.cast}
    rules_dir = ROOT / "rules"
    before_holding_cents = sum(
        hold_day_cost_cents(cast_by_id[cast_id], day, rules_dir)
        for cast_id, days in before_held.items()
        if paid[cast_id]
        for day in days
    )

    facts = json.loads((ROOT / "docs" / "FACTS.json").read_text(encoding="utf-8"))
    checks = {
        "holding_before_cents": (before_holding_cents, facts["holding_before_cents"]),
        "hold_days_before": (before_hold_days, facts["hold_days_before"]),
        "hold_days_after": (solved.result.hold_days, facts["hold_days_after"]),
        "holding_after_cents": (solved.result.holding_cents, facts["holding_after_cents"]),
    }
    drift = {name: pair for name, pair in checks.items() if pair[0] != pair[1]}
    if drift:
        raise SystemExit(
            "this fixture disagrees with docs/FACTS.json, which is the authority for every headline "
            "number (PLAN.md D7). Re-run scripts/facts.py first, or fix this script. "
            + "; ".join(f"{name}: ours {ours}, FACTS {theirs}" for name, (ours, theirs) in drift.items())
        )

    payload = {
        "_generated_by": "web/scripts/capture_demo_board.py from a real solver and checker run",
        "_generated_at": datetime.now(UTC).replace(microsecond=0).isoformat(),
        "_run_sha": _run_sha(),
        "_note": (
            "Constructed demo data (PLAN.md D8): cast are letters, not names. The rule side is real. "
            "This file is the offline snapshot only; the app reads the live API whenever it answers."
        ),
        "schedule": json.loads(schedule.model_dump_json()),
        "before": {
            "day_scene_ids": {str(d): ids for d, ids in before_full.items()},
            "scene_order": before_raw["scene_order"],
            "hold_days": before_hold_days,
            "holding_cents": before_holding_cents,
            "verdicts": [json.loads(v.model_dump_json()) for v in before_verdicts],
        },
        "after": {
            "day_scene_ids": {str(d): ids for d, ids in after_map.items()},
            "result": json.loads(after.model_dump_json()),
        },
    }

    out = ROOT / "web" / "src" / "fixtures" / "demo-board.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    illegal = [v.day for v in before_verdicts if v.status == "ILLEGAL"]
    print(
        f"wrote {out.relative_to(ROOT)}: before hold_days={before_hold_days} "
        f"illegal_days={illegal} after hold_days={after.pass2.hold_days} status={after.pass2.status}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
