#!/usr/bin/env python
"""
Task 6.5, desktop half: every http(s) URL and every repository path linked from README.md and JUDGE.md,
fetched or stat'ed, printed as a markdown table (status, title, expected). Run before every submission
edit and commit the table as docs/links-check.md.

    uv run python scripts/check_links.py > docs/links-check.md
"""
from __future__ import annotations

import datetime
import re
import sys
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SURFACES = ("README.md", "JUDGE.md")
_URL = re.compile(r"https?://[^\s)>\]`\"']+")
_PATH = re.compile(r"\]\(([A-Za-z0-9_./-]+)\)")


def fetch(url: str) -> tuple[str, str]:
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0 (HOLD link check)"})
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            body = r.read(200_000).decode("utf-8", "ignore")
            title = re.search(r"<title[^>]*>(.*?)</title>", body, re.S | re.I)
            return str(r.status), (title.group(1).strip()[:80] if title else "(no title)")
    except urllib.error.HTTPError as exc:
        return str(exc.code), "refuses scripted fetches" if exc.code == 403 else "HTTP error"
    except Exception as exc:
        return "ERR", type(exc).__name__


def main() -> int:
    urls: dict[str, str] = {}
    paths: dict[str, str] = {}
    for name in SURFACES:
        text = (ROOT / name).read_text(encoding="utf-8")
        for u in _URL.findall(text):
            urls.setdefault(u.rstrip(".,"), name)
        for p in _PATH.findall(text):
            if not p.startswith("http"):
                paths.setdefault(p, name)
    print(f"# Link check, {datetime.date.today().isoformat()}\n")
    print("Generated by `scripts/check_links.py` over README.md and JUDGE.md.\n")
    print("| Surface | Target | Status | Title or note |\n|---|---|---|---|")
    bad = 0
    for u, name in sorted(urls.items()):
        if re.match(r"https?://(localhost|127\.0\.0\.1)", u):
            print(f"| {name} | {u} | skipped | local address from the quick start |")
            continue
        status, title = fetch(u)
        ok = status.startswith("2") or status == "403"
        bad += not ok
        print(f"| {name} | {u} | {status} | {title} |")
    for p, name in sorted(paths.items()):
        exists = (ROOT / p).exists()
        bad += not exists
        print(f"| {name} | `{p}` | {'exists' if exists else 'MISSING'} | repository path |")
    print(f"\n{bad} problem(s)." if bad else "\nEvery link answered.")
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
