#!/usr/bin/env python
"""
Generate api/agents/event_agent/evalset.json, the interpreter's eval set.

The prompt each case sends is the context block the running service builds plus the sentence, so
it is generated by calling the service's own `_event_context` rather than pasted. A pasted prompt
drifts: the call-sheet case in the other eval set drifted from its sample once already, and the
gold answer then quoted a rate the prompt no longer contained. Here the drift is impossible,
because the prompt has one definition and this file is checked against it.

    uv run python -m scripts.event_evalset            # write it
    uv run python -m scripts.event_evalset --check    # fail if the committed file is stale
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from api.agents.hold_agent.runner import _event_context

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "api" / "agents" / "event_agent" / "evalset.json"
DEMO = ROOT / "data" / "demo" / "hold-demo.json"

# Three that apply and one that must refuse. The weather case is here because it is the one the
# first live run got wrong: it named the day in its reading and left the payload empty, which is
# the defect the named fields fixed. The refusal is here because an interpreter that forces every
# sentence into the nearest of three kinds is worse than one that asks.
CASES: list[tuple[str, str, dict[str, object]]] = [
    (
        "event_actor_late",
        "B is out on Thursday",
        {"status": "ok", "kind": "actor_late", "cast_id": "cB", "scene_id": None, "day_index": 3,
         "questions": [], "reading": "Cast member B cannot work on Thursday, day 4."},
    ),
    (
        "event_weather_cover",
        "Rained out Wednesday, nothing exterior is happening",
        {"status": "ok", "kind": "weather_cover", "cast_id": None, "scene_id": None, "day_index": 2,
         "questions": [], "reading": "No exterior scene can shoot on Wednesday, day 3."},
    ),
    (
        "event_scene_dropped",
        "Cut scene 6, we are not shooting it",
        {"status": "ok", "kind": "scene_dropped", "cast_id": None, "scene_id": "s6", "day_index": None,
         "questions": [], "reading": "Scene 6 is dropped and will not be shot."},
    ),
    (
        "event_out_of_scope",
        "We lost the barn location for the whole week",
        {"status": "needs_clarification", "kind": None, "cast_id": None, "scene_id": None, "day_index": None,
         "questions": ["Losing a location is not one of the three events this reads. Should specific scenes be dropped instead, or is this weather?"],
         "reading": "A location was lost for the week, which is not an actor being unavailable, a scene being dropped, or weather cover."},
    ),
]


def demo() -> dict[str, object]:
    return {k: v for k, v in json.loads(DEMO.read_text(encoding="utf-8")).items() if not k.startswith("_")}


def render() -> str:
    context = _event_context(demo())
    return json.dumps(
        {
            "eval_set_id": "hold_events_v1",
            "name": "hold_events_v1",
            "description": "The event interpreter: one sentence about what happened on set, one typed HOLD event, or the question it needs answered. Three that apply and one that must refuse.",
            "eval_cases": [
                {
                    "eval_id": eval_id,
                    "conversation": [
                        {
                            "invocation_id": f"{eval_id}-1",
                            "user_content": {"role": "user", "parts": [{"text": f"{context}\n\nWhat happened: {sentence}"}]},
                            "final_response": {"role": "model", "parts": [{"text": json.dumps(gold, indent=1)}]},
                            "intermediate_data": {"tool_uses": [], "tool_responses": [], "intermediate_responses": []},
                        }
                    ],
                    "session_input": {"app_name": "hold", "user_id": "eval", "state": {}},
                }
                for eval_id, sentence, gold in CASES
            ],
        },
        indent=1,
    ) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="fail if the committed file is not what this renders")
    args = parser.parse_args()
    rendered = render()
    if args.check:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != rendered:
            print(f"{OUT.relative_to(ROOT)} is stale; run: uv run python -m scripts.event_evalset", file=sys.stderr)
            return 1
        print(f"{OUT.relative_to(ROOT)} is current")
        return 0
    OUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
